language: ruby
rvm:
- 2.4.1

before_script:
 - chmod +x ./scripts/build_jekyll_maven.sh # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/build_jekyll_maven.sh

# branch whitelist
branches:
  only:
    - haDeployment

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: haDeployment

env:
  global:
  - secure: jK3xUFjgY6oWNq91PuBQL9AAQ5kYQsWsrczhKaJvGh3xWGV4WYLPGIG3dXXf4gXzEnOrzw99vBRZdxQxmT7dDjTJzl3GXRSP11b+oQqK5SNWcQfr6tyI4sH2SPIvbYKjq5N/oEOMbAW9LSGaDTbfHJlacsEaV/3+zImC+iPmpK+z5Np52IDvMhEsNdZ4pfYRTrCXLdpDnkmYmkboXXaA3R+eAnoNdruTGVipHQ4ozyn/F6l4CXp+Vrx7kGWubXMpITR65Fh7PUtT8+WARrcd7Wmwaz3ZQE0Lp5yoPRWGoFdEQ3bgHe9XdPs9OuQs5cjxTH6w4ek8w/wu4mTLlE7jGAo6EvDoMXV6fYR1iceduxfWXTuNIl+qh3tNWUsqDUiXIftqfG7Mrrtr9t8cPwCEgDBV4iYWPRoDuNyRpynIJnlEasNG46TdwCbdnchG17x4GBNISFVJRi9vVa1xZGE7wXJCf5fqbT7Efcn+rOu5PHOuWfzrRstm4iv0u1jR54hnwjwsUI432qX4zq9NvqWewhJyBJW17zQRH3U7IjdKhdA0ZsbgpheG/ipNXQO8dCXuYOtAzf219UuVysZquqJ4NGlLfbtBTo05GDrwuHurE0D+3I7aSO7Q8itmG9oxCzzsO4/g6lQI0j2M3YRs4ex0RAOY0XgauKS9/IoSr49dXUM=
  - secure: FOaWoUPmXQXgkWVrQAKNaiykHcyCrQFEbX98zhVkv8rDsGWZoqbdjLEKgHC/4AU5iqMRkeWUVE+ZzeIzSuyZjcVvGyaW+mcaYqs/2HVC/l4CkVQI9gCUQZKFV36eimxZn04BWycQh2LcDp4s/oAx4RyXAffItY0cDi+nxXIFodz1tZxcNpMnQGlmbVnqjVdHQnGZxODoaBJa/IZb9a4Mm0GGfywLdS6WHXAi+e+LGimT3bbyZ99KwIZapanUAX8lJof1glIo8RpwPHyVppuXnHCa923pDdpTLVuzmxJ+x9lq6nEoplDPZIcFzfTxE5/wIrl8WMu/EUMXVCGYt46CwesquSu5DXyEIq3PUFvLUyOYqVqnAtKvpJU2GRVvsIOFzrcvoutK08xQtXcDo6MGdpGN5OaVBEB4O/hRm/WuIWuCUu/58QNRNda4RqhEcZpoUTKvHQta2eOmlM4xWGrW5qEilna14ad0VwQUlHetsHc+pN0Ym2mGUvkVbnh9fl5D6oSpyd/UB2QjhDgIscmuJCxcFs1XUShMptjh1cnxGjNP8IQPzXt8wavL9/pD1NcrCsrlDw6gGm9sfFJG+A3i7zeVIKIJyoyADY6CGhWMQwxaiqY099ZmZfmHCr3aVnMPPdIggH1Tdd7cDGZWlZe0WRy//jp7AgONj82SDI2ihFE=
  - secure: tAWhCGtX5zKnHlDryzYnAWwZiupfHOVtxOvj8w1iDfFvcVWP4Rfkn2OWMJPaxYl+HIbpmJjCtH6+l9iplkF3FuKq5RLXvxa7nZIpDWrp4mhR/7CzhATCHljdMVyNNZDC6lyMDrApQxeptebubqL1OW5niDAKfRMIccVVDwNlMSuknnJ08/bU/VDUvobFgyWRc90pLoy0fPe4paEH2T9R1EW1bP7am771A7INfxOqxLP7rtUnYll2WVdLItPkijJ91dUo0qadQVJcO7DR2cMc3iw3Q/efsQIAwTMPJMqROILqqeVcod0mvJx2y85l27JeZfMADBv9c+OeyZeRWVZdG77KdT+lX2h5XFkPMphsArwmxFeL16Bq0kxJmd2KA8HeFZ1rGM+RV0HiF0rvhq+WEZ551v22nXilRZ8RlmQrUlefPHo2s8X8TvV9g6Y1bSGIwTDa9iLIRBUhfgyy9FKGJaen03YuIKCLd7a/rxOO0xSzVXwF5NVcE/Hm3DFC9qMcH0T5cSoVDwOs8pFhs7ebF6AiAbljEA91yqJjqQEKWFJX4pCR93bopHflEet3D77XWf3PY6aH8wKdwNMRtrXV43ay8tma5wWVzgJvbmGy4W276+KPrv/OMC2ncYNm9lbLOa3EQp2wYaY4pcgxc9Nu2Hk/ld2ef9AUz+J2qE7Clyg=
  - secure: KxpYj1dOKeM4XxXHoIx7eLDnWHrPyUmnKap2AVV2MIYe4XSBPreXp7XOEzo8UVyckufY6BvHGnfI6B1RS+9M9k0/viWwdtJBgJyVf/A9awQrN460SIyQ8IDGT4j5P1SMUUls9tni9PAuYvka+p6Hunjm2b7SfOZj9tnOQNAl9KMuQxEsvootkHbFZdOaxct+THq4O9hs7eInhc4CwI4s/YL5KuWYwYjKHEv/A5775Myq9OPYwk17zsj7gpyngjhUYKnr1CWsu8COFpKbMWtt1UKaviKTw+pWQ1KwX/0dtOEFdrQ9uZuHWJdUHfPMUAp6povquCsm2yyAkM1LV3qPJ30E6SvFm1Vci2c2wluPxUPChl/9L8oQXx0ebKGSeiEbYqlISgldjwls5RaLwIwsuxChk138//pYBmo1eQeDi/jaaiZEMQ+iWKoCEttyB2TsoiN3vfINlwj/TsUoWH9j2JtMfoy3RMygvmFMAXSN39KP+YIETbJ28ZkVzDh0HBdTysdbiY+TwAPSdr9YnW0FPaEvfXqGDsEz+rE/AO4dt0EToT/zNJ+t/chs2h7Is/XHX9wMti5+ySRkd5AYLHR3tBg6Dcpm7lJdlTTvIbHr8G3vdu7/Sr5FRQIwkKhdKD4Umi9xhtJk3z4tgQ4dKN+/Zfh35JrE3TRZQremCE8YhlY=

